name: Licenses
on:
  workflow_dispatch:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
jobs:
  licences:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Submodule Update
        run: |
          cd ${{ github.workspace }}
          cwd=$(pwd)
          git submodule update --init --recursive
      - name: Install Dependencies
        run: yarn install
      - name: Get Repository License
        id: license
        run: |
          license="${{ (github.event.repository.license.spdx_id) || (github.event.repository.licenses[0]) }}"
          echo "License detected: $license"
          echo "license=$license" >> $GITHUB_OUTPUT
      - name: Check Licenses - Backend
        uses: ONLYOFFICE/check-licenses@v1
        with:
          project_license: ${{ steps.license.outputs.license }}
          working_directory: ./backend
      - name: Check Licenses - Frontend
        uses: ONLYOFFICE/check-licenses@v1
        with:
          project_license: ${{ steps.license.outputs.license }}
          working_directory: ./frontend
